services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: wahoothoots
    # Adding network configuration for local network accessibility
    networks:
      - postgres-network

# Define the network to ensure proper connectivity
networks:
  postgres-network:
    driver: bridge